server:
  port: 9090

spring:
  application:
    name: kanban-board

  datasource:
    url: jdbc:postgresql://localhost:5432/kanban-board
    username: postgres
    password: Pas$1212
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/kanban-board

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
